global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules.yml"

scrape_configs:
  - job_name: 'smoke-detection-metrics'
    static_configs:
      - targets: ['metrics_simulator:8000']
    metrics_path: '/metrics'

  - job_name: 'flask-api-metrics'
    static_configs:
      - targets: ['flask_api:5000']
    metrics_path: '/metrics'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']