# Base image with Python 3.10
FROM python:3.10

# Set working directory
WORKDIR /app

# Copy requirements and install
COPY requirements.txt .

RUN pip install -r requirements.txt

RUN mkdir -p ./app/utils ./data_ingestion ./config ./data_processing/

# Copy data_ingestion folder into container
COPY ../data_ingestion/ ./data_ingestion/
COPY ../config/ ./config/
COPY ../app/utils/ ./app/utils/
COPY ../.env ./
COPY ../data_processing/utils.py ./data_processing/

